name: Docker Image CI

on:
  push:
    branches: [ main, test-docker ]

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:latest

  push_to_registry:
    name: Push the Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $GITHUB_REPOSITORY:latest
